-- AlterTable
ALTER TABLE "Batch" ADD COLUMN     "honeyCertified" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "honeyRemaining" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "totalHoneyCollected" DOUBLE PRECISION NOT NULL DEFAULT 0;
